### ISSUE TITLE
NAMESPACE file missing in package

### ISSUE THREAD

**Issue by selwyn-mccracken** [Dralliag/opera#1]
Hi,

I have R 3.2.2 on Win7 and when installing via devtools::install_github('Dralliag/opera') I trigger the following error "ERROR: a 'NAMESPACE' file is required" 

Apparently packages for R > 3 require a NAMESPACE file according to this SO answer: http://stackoverflow.com/a/18590645.

I successfully installed opera by following those instructions - i.e. cloning locally then adding a NAMESPACE file that contained exportPattern( "." ) 

Nice package btw.

**Comment by Dralliag** [comment]
Hi, sorry for the delayed response and thx for the comment. 
This issue is actually because the documentation files and the NAMESPACE file of the package are generated automatically with roxygen2. They are thus not in the githup repo. To install the package, the simplest way is to use the devtools package of R:

install.packages("devtools")
install.packages("roxygen2")
library(devtools)
library(roxygen2)
install_github("dralliag/opera")

You may need to install some package such as testthat if asked by R.
Best
