### ISSUE TITLE
ML-Prod

### ISSUE THREAD

**Issue by lviano** [Dralliag/opera#10]
Hello Pierre,

Thank you for your work!
I was looking at the code in MLProd.R at line 55 that I report here:
`R <- neweta/eta[t, ] * R + log(1 + awake[t, ] * neweta * (c(c(lpred) - lexp))) `
Is it correct that the term `neweta/eta[t, ]` multiplies only R and not also `log(1 + awake[t, ] * neweta * (c(c(lpred) - lexp)))` ?

I am asking this because as ,shown in the attached pdf 
[Counts (1).pdf](https://github.com/Dralliag/opera/files/5040777/Counts.1.pdf)
, taking the log of the weight update expression in Algorithm 2 of the  [original paper](https://arxiv.org/pdf/1402.2044.pdf ) and replacing R to be the logarithm of the weights I obtained that the learning rates ratio multiplies both the terms, namely:
`R <- neweta/eta[t, ] *( R + log(1 + awake[t, ] * neweta * (c(c(lpred) - lexp)))) `.

Could you just check and confirm if that line of code is correct?

Thank you in advance,
Luca

**Comment by Dralliag** [comment]
Hi Luca,

Sorry for the late response. You are right there is a mismatch between the code and the theoretical algorithm as it is described in the paper. 

Yet, in the original paper the theoretical update is 
	R <- neweta/oldeta * ( R + log(1 + awake[t, ] * oldeta * (c(c(lpred) - lexp))))
and not
	R <- neweta/oldeta * ( R + log(1 + awake[t, ] * neweta * (c(c(lpred) - lexp))))
as you suggest.
In other words, it is the previous version of eta (i.e., oldeta = eta[t,] and neweta = eta[t+1,]) which is used inside the logarithm. 
This is possible in theory since the theoretical paper assumes that the losses are bounded in [0,1]. But in practice, the range of the losses is unknown.  "oldeta" cannot be used inside the logarithm because it might be too large and the logarithm may be undefined (because the value inside can be negative). This is why in practice, I preferred to replace oldeta inside the logarithm with neweta (which ensures that the logarithm is defined whatever the loss range is) and not consider the multiplicative factor (neweta / oldeta) in front of the logarithm to compensate this change. I thus prefer to keep the current implementation. 

Asymptotically, the theoretical update, your update, and the one which is implemented should be approximately the same and all should work fine! 

I hope that I helped,
Best,

Pierre

**Comment by lviano** [comment]
Hello,

I am grateful for your clear answer that fully solves my doubts.

Best regards,
Luca
