### ISSUE TITLE
MLPol

### ISSUE THREAD

**Issue by IvanVigor** [Dralliag/opera#8]
Dear Pierre,

I was checking the code related to the MLpol. I noticed that this code is expressed as ML-Poly algorithm in the readme page. This is true because the main computation is the same but there is a row of code that is different compared to the theoretical one of ML-Poly. I'm referring to these lines of code:

 newB <- max(B, max(r^2))
eta[t + 1, ] <- 1/(1/eta[t, ] + r^2 + newB - B)
B <- newB

Here is supposed that you are updating the learning rate. But why using newB - B? Is this a new version? If yes, where can I find additional information about it?

Thank you in advance,
Yours Sincerely
Ivan

**Comment by IvanVigor** [comment]
No news?

**Comment by brkbrc** [comment]
have you compared the original paper where ML-poly is explained?

**Comment by IvanVigor** [comment]
Yes, I have checked that this aspect is not mentioned.

**Comment by Dralliag** [comment]
Hi Ivan,

Yes in the original paper. The errors (or the gradients) are supposed to be bounded into [0,1]. 
If the data are not normalized this is not true in practice and one needs to modify a bit the learning rates. Here we suppose that such a bound, called B, is unknown in advance and updated sequentially.

This update: 
```
newB <- max(B, max(r^2))
```
corresponds to updating an empirical bound on the errors (or on the gradients if the gradient option is chosen). As I said, it was not needed in the original paper since B was supposed to be known and equal to 1.

Then, the update
```
eta[t + 1, ] <- 1/(1/eta[t, ] + r^2 + newB - B)
B <- newB
```
corresponds to updating the learning rate as mensioned in the original paper (cf. Thm 5) as:
```
eta[t+1] = 1/ (newB + sum_{s=1}^{t+1} r[s]^2)
```
except that the bound 1 in the original paper is replaced by newB and that the update is done sequentially from eta[t].

I hope that I helped. Sorry for the very late reply. I thought the subject was outdated.
Best,

Pierre

**Comment by IvanVigor** [comment]
Thank you Pierre! :+1:  Little bit late but I applied a lot your library. You can close the "Issue"
